Disable thread safety analysis checks for connectedhomeip (#10279)
This fixes compilation errors of the form:

```
...
Step #3 - "compile-centipede-address-x86_64": [1m../../src/platform/Linux/ConnectivityManagerImpl.h:211:46: [0m[0;1;31merror: [0m[1m'guarded_by' attribute requires arguments whose type is annotated with 'capability' attribute; type here is 'std::mutex' [-Werror,-Wthread-safety-attributes][0m
Step #3 - "compile-centipede-address-x86_64":     static GDBusWpaSupplicant mWpaSupplicant CHIP_GUARDED_BY(mWpaSupplicantMutex);
Step #3 - "compile-centipede-address-x86_64": [0;1;32m                                             ^
Step #3 - "compile-centipede-address-x86_64": [0m[1m../../src/system/SystemMutex.h:75:49: [0m[0;1;30mnote: [0mexpanded from macro 'CHIP_GUARDED_BY'[0m
Step #3 - "compile-centipede-address-x86_64": #define CHIP_GUARDED_BY(x) CHIP_TSA_ATTRIBUTE__(guarded_by(x))
Step #3 - "compile-centipede-address-x86_64": [0;1;32m                                                ^
Step #3 - "compile-centipede-address-x86_64": [0m1 error generated.
```

as reported in
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=58531

Also updated the dockerfile to checkout less things from CHIP so that
the checkout step is faster.

---------

Co-authored-by: Andrei Litvin <andreilitvin@google.com>